# Generated by Django 4.0.5 on 2022-07-09 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='city',
        ),
        migrations.AddField(
            model_name='city',
            name='offers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='travels.offer'),
        ),
    ]
