# Generated by Django 4.0.5 on 2022-07-09 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0002_remove_offer_city_city_offers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('slug', models.SlugField(blank=True, default='')),
                ('offers', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='travels.offer')),
            ],
        ),
    ]
