# Generated by Django 4.0.5 on 2022-07-09 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0003_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='offers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='travels.city'),
        ),
    ]
