# Generated by Django 4.0.5 on 2022-07-10 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0007_service_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='currency',
            field=models.CharField(choices=[('EUR', 'Euro'), ('USD', 'Dollars'), ('RUB', 'Rubles')], default='R', max_length=3),
        ),
    ]
