# Generated by Django 4.0.5 on 2022-07-15 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0009_alter_service_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.ManyToManyField(to='travels.service')),
                ('user', models.ManyToManyField(to='travels.user')),
            ],
        ),
    ]
