# Generated by Django 4.0.5 on 2022-07-15 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0011_comment_remove_favorite_user_remove_favorite_service_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='travels.service'),
        ),
    ]
